[package]
name = "brainlift"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.42", features = ["derive"] }
cranelift = "0.122.0"
cranelift-module = "0.122.0"
cranelift-object = "0.122.0"
libc = "0.2.174"
